kind: pipeline
type: docker
name: docs

workspace:
  base: /app
  path: drone/docs

clone:
  disable: true

steps:
  - name: clone
    pull: if-not-exists
    image: alpine/git:v2.30.2
    commands:
    - echo $DRONE_GIT_URL
    - git clone $DRONE_GIT_URL .

---
kind: secret

external_data:
  DRONE_GIT_URL:
    path: drone/data/docs
    name: DRONE_GIT_URL
