kind: pipeline
type: docker
name: default

clone:
  disable: true

volumes:
- name: cache
  host:
    path: /home/ubuntu/data/drone/cache

steps:
- name: clone
  image: alpine/git:v2.30.2
  pull: if-not-exists
  environment:
    DRONE_GIT_URL:
      from_secret: drone_git_url
    SSH_KEY:
      from_secret: ssh_key
  commands:
    - echo $DRONE_GIT_URL
    - mkdir -p /root/.ssh/
    - echo "$$SSH_KEY" > /root/.ssh/id_rsa
    - chmod -R 600 /root/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone -v $DRONE_GIT_URL .

- name: restore-cache
  pull: if-not-exists
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: install+build # install
  image: node:16.9-alpine
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  commands:
    - yarn config set ignore-engines true
    - yarn config set registry https://registry.npm.taobao.org/
    - yarn config set cache-folder "/cache"
    - yarn install
    - yarn run build

- name: rebuild-cache
  pull: if-not-exists
  image: drillster/drone-volume-cache
  volumes:
    - name: cache
      path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

---
kind: secret
name: drone_git_url
get:
  path: drone/data/docs
  name: drone_git_url
---
kind: secret
name: ssh_key
get:
  path: drone/data/docs
  name: ssh_key
