kind: pipeline
type: docker
name: docs

workspace:
  base: /app
  path: drone/docs

clone:
  disable: true

steps:
- name: clone
  image: alpine/git:v2.30.2
  pull: if-not-exists
  environment:
    DRONE_GIT_URL:
      from_secret: drone_git_url
    SSH_KEY:
      from_secret: ssh_key
  commands:
    - echo $DRONE_GIT_URL
    - mkdir -p /root/.ssh/
    - echo "$$SSH_KEY" > /root/.ssh/id_rsa
    - chmod -R 600 /root/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone -v $DRONE_GIT_URL .

- name: 加载缓存
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./node_modules
    - ./.npm-cache

- name: install # install
  image: node:16.9-alpine
  pull: if-not-exists
  commands:
    - npm config set cache ./.npm-cache --global
    - npm install

- name: build
  image: node:16.9-alpine
  commands:
    - npm run build

- name: 构建缓存
  image: drillster/drone-volume-cache
  detach: true
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./.npm-cache
    - ./node_modules

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

---
kind: secret
name: drone_git_url
get:
  path: drone/data/docs
  name: drone_git_url
---
kind: secret
name: ssh_key
get:
  path: drone/data/docs
  name: ssh_key

volumes:
- name: cache
  host:
    path: /home/ubuntu/data/drone/cache/node_modules
