kind: pipeline
type: docker
name: docs

workspace:
  base: /app
  path: drone/docs

clone:
  disable: true

steps:
  - name: clone
    pull: if-not-exists
    image: alpine/git:v2.30.2
    environment:
      DRONE_GIT_URL:
        from_secret: drone_git_url
    commands:
      - echo $DRONE_GIT_URL

trigger:
  branch:
    - main
  event:
    - push

---
kind: secret
name: drone_git_url
get:
  path: drone/data/docs
  name: drone_git_url

