---
kind: pipeline
type: docker
name: docs

steps:
- name: 打包
  settings:
    mirror: https://docker.mirrors.ustc.edu.cn
  image: node:16.9-alpine
  pull: if-not-exists
  commands:
    - yarn config set registry https://registry.npm.taobao.org/
    - yarn install
    - yarn run build

- name: 上传
  image: plugins/docker:20.10.9
  pull: if-not-exists
  privileged: true
  settings:
    mirror: https://docker.mirrors.ustc.edu.cn
    daemon_off: false
    repo: registry.cn-shanghai.aliyuncs.com/wssio/docs
    registry: registry.cn-shanghai.aliyuncs.com
    cache_from: registry.cn-shanghai.aliyuncs.com/wssio/docs
    auto_tag: true
    cache_from: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

---
kind: secret
name: docker_username
get:
  path: drone/data/docs
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone/data/docs
  name: docker_password
