---
kind: pipeline
type: docker
name: docs

steps:
- name: 打包
  image: node:16.13.1-alpine
  pull: if-not-exists
  commands:
    - yarn install --force
    - yarn run build

- name: 上传
  image: plugins/docker:latest
  pull: if-not-exists
  privileged: true
  settings:
    daemon_off: false
    repo: image.wssio.com/docs
    registry: image.wssio.com
    cache_from: image.wssio.com/docs
    auto_tag: true
    cache_from: true

- name: 部署
  image: appleboy/drone-ssh:latest
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - list=$(sudo docker ps -a| grep docs-service* | awk '{print $1}')
      - test "$list" = "" && echo "none docs-app containers running" || sudo docker stop $list
      - test "$list" = "" && echo "none docs-app containers running" || sudo docker rm $list -f
      - sudo docker rmi image.wssio.com/docs:latest
      - sudo docker run -d -v /home/ubuntu/data/docs:/var/log/nginx -p 8081:8081 --name=docs-service image.wssio.com/docs:latest

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

---
kind: secret
name: docs_git_url
get:
  path: drone/data/docs
  name: docs_git_url
---
kind: secret
name: ssh_host
get:
  path: drone/data/docs
  name: ssh_host
---
kind: secret
name: ssh_username
get:
  path: drone/data/docs
  name: ssh_username
---
kind: secret
name: ssh_password
get:
  path: drone/data/docs
  name: ssh_password

---
kind: pipeline
type: docker
name: notify

clone:
  disable: true

steps:
- name: 通知1
  image: drillster/drone-email:latest
  pull: if-not-exists
  settings:
    recipients: [longzinziyan@gmail.com,2811416050@qq.com]
    recipients_only: true
    subject: "Drone build: [{{ build.status }}] {{ repo.name }} ({{ repo.branch }}) #{{ build.number }}"
    host: smtp.qq.com
    port: 587
    from: 1296114084@qq.com
    username:
      from_secret: email_user
    password:
      from_secret: email_password

trigger:
  status: [success, failure]

depends_on: [docs]

---
kind: secret
name: email_user
get:
  path: drone/data/docs
  name: email_user
---
kind: secret
name: email_password
get:
  path: drone/data/docs
  name: email_password
