{
 "title": "Docker 容器指标监控",
 "description": "Docker 容器指标监控",
 "tags": [
  "docker",
  "Containers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "容器运行时间",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU  负载",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "内存 负载",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "存储 负载",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"ext4\"} - node_filesystem_free_bytes{fstype=\"ext4\"}) / node_filesystem_size_bytes{fstype=\"ext4\"}  * 100"
    }
   ]
  },
  {
   "title": "已用存储",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"nodeexporter\"} - node_filesystem_free_bytes{job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU 核心数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "系统 负载",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "容器 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\",container_label_org_label_schema_group=\"wssio\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "容器内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"wssio\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "容器缓存内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"wssio\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器网络输入",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"wssio\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "容器网络输出",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"wssio\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}