{
 "title": "服务指标监控",
 "tags": [
  "prometheus",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance\"}, nodename)"
    }
   },
   {
    "name": "interval",
    "label": "时间间隔",
    "query": "30s,1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "服务器整体状态 当前选中主机：$show_hostname，实例：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "服务器资源总览表",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\n连接数：CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数。",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"nodeexporter\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"nodeexporter\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexporter\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"nodeexporter\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"nodeexporter\"} / (node_memory_MemTotal_bytes{job=\"nodeexporter\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"nodeexporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"nodeexporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"nodeexporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"nodeexporter\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"nodeexporter\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"nodeexporter\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"nodeexporter\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"nodeexporter\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"nodeexporter\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "主机运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU 空闲",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "CPU 内核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_physical_cores" }
   ]
  },
  {
   "title": "已用内存",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "剩余存储空间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{})"
    }
   ]
  },
  {
   "title": "整体总负载与整体平均CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(node_load5{})", "legendFormat": "总5分钟负载" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'})",
     "legendFormat": "总核数"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总内存与整体平均内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "总内存量" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"nodeexporter\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"nodeexporter\"} - node_memory_MemAvailable_bytes{job=\"nodeexporter\"})",
     "legendFormat": "总已用"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"nodeexporter\"} - node_memory_MemAvailable_bytes{job=\"nodeexporter\"}) / sum(node_memory_MemTotal_bytes{job=\"nodeexporter\"}))*100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总磁盘与整体平均磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "总磁盘量" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"nodeexporter\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  { "title": "服务明细：【$show_hostname】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU IO wait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"} / (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})*100 /(node_filesystem_avail_bytes {instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "根分区使用率"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=\"node-exporter:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\"} + 1))) * 100",
     "legendFormat": "交换分区使用率"
    }
   ]
  },
  {
   "title": "各分区可用空间(EXT.*/XFS)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 18 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "每小时流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=\"node-exporter:9100\",device=~\"eth0|lo\"}[60m])",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=\"node-exporter:9100\", device=~\"eth0|lo\"}[60m])",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "总文件描述符",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=\"node-exporter:9100\"})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"} / (node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "每秒网络带宽使用",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"node-exporter:9100\", device=~\"eth0|lo\"}[$interval])*8",
     "legendFormat": "下载"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"node-exporter:9100\", device=~\"eth0|lo\"}[$interval])*8",
     "legendFormat": "上传"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter:9100\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{instance=\"node-exporter:9100\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=\"node-exporter:9100\"}",
     "legendFormat": "15分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "读取"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "写入"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=\"node-exporter:9100\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗时占比",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "每秒I/O操作%"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"node-exporter:9100\"}[$interval]) / rate(node_disk_reads_completed_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"node-exporter:9100\"}[$interval]) / rate(node_disk_writes_completed_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "{{device}}_加权"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"node-exporter:9100\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"node-exporter:9100\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=\"node-exporter:9100\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"node-exporter:9100\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=\"node-exporter:9100\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "使用的文件描述符" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=\"node-exporter:9100\"}",
     "legendFormat": "使用的文件描述符"
    },
    {
     "expr": "rate(node_context_switches_total{instance=\"node-exporter:9100\"}[$interval])",
     "legendFormat": "每秒上下文切换次数"
    }
   ]
  },
  {
   "title": "I/O 使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "报警",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Prometheus 指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
       "legendFormat": "Target heap size"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "Allocations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "HTTP 请求",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP 请求花费的时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "查询引擎时间",
     "type": "timeseries",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[1m])",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "HTTP 请求延迟",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum[1m]) / rate(prometheus_http_request_duration_seconds_count[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  }
 ]
}