{
 "title": "Traefik 服务指标监控",
 "description": "Simple dashboard for Traefik 2",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus",
  "Traefik 2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务:",
    "query": {
     "query": "label_values(traefik_service_requests_total{job=\"traefik\"},service)"
    }
   },
   {
    "name": "protocol",
    "label": "协议:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "interval",
    "label": "周期:",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "服务器运行时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "每个状态码的请求",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (OriginStatus) (count_over_time({job=\"wssio\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": " {{OriginStatus}}"
    }
   ]
  },
  {
   "title": "服务器错误 $interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5\\\\d\\\\d\",job=\"traefik\",service=~\"$service\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "请求路由数",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (RouterName) (count_over_time({job=\"wssio\"}|= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{RouterName}}"
    }
   ]
  },
  {
   "title": "成功响应数 $interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(traefik_service_requests_total{code=~\"(2|3)\\\\d\\\\d\",service=~\"$service\",job=\"traefik\",protocol=~\"$protocol\"}[$interval])))"
    }
   ]
  },
  {
   "title": "总字节数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({job=\"wssio\"}|= \"RequestProtocol\" | json | OriginStatus=200 | unwrap DownstreamContentSize |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "客户端错误 $interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4\\\\d\\\\d\",job=\"traefik\", service=~\"$service\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "请求时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=\"wssio\"} |= \"RequestProtocol\"| json | unwrap Duration |  __error__=\"\"  [$__interval]) by (ServiceName)",
     "legendFormat": " {{ ServiceName }}"
    }
   ]
  },
  {
   "title": "请求体大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (ServiceName) (sum_over_time({job=\"wssio\"} |= \"RequestProtocol\" |json | unwrap RequestContentSize |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ ServiceName}}"
    }
   ]
  },
  {
   "title": "Top5 响应码 $interval",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, sum(increase(traefik_service_requests_total{protocol=~\"$protocol\", job=\"traefik\", service=~\"$service\"}[$interval])) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traefik入口平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{job=\"traefik\"}) / sum(traefik_entrypoint_requests_total{job=\"traefik\"}) * 1000"
    }
   ]
  },
  {
   "title": "所有状态码 $interval",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(increase(traefik_service_requests_total{protocol=~\"$protocol\", job=\"traefik\", service=~\"$service\"}[$interval]), \"response_code\",  \"$1,xx\", \"code\", \"(\\\\d).+\")) by (response_code)",
     "legendFormat": " {{response_code}}"
    }
   ]
  },
  {
   "title": "每个服务平均响应时间 $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{job=\"traefik\",service=~\"$service\",protocol=~\"$protocol\"}[$interval])) by (service) / sum(increase(traefik_service_request_duration_seconds_count{job=\"traefik\",service=~\"$service\",protocol=~\"$protocol\"}[$interval])) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "客户端请求 $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\",job=\"traefik\"}[$interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "获得服务数 $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik\", protocol=~\"http|https\", service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "服务器错误趋势 $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\",service=~\"$service\",code=~\"5\\\\d\\\\d\",protocol=~\"$protocol\" }[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "客户端错误趋势 $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\",service=~\"$service\",code=~\"4\\\\d\\\\d\",protocol=~\"$protocol\" }[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Traefik入口点连接数 $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_open_connections{job=\"traefik\"}[$interval])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "$service - 连接数 $interval ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_open_connections{service=~\"$service\",job=\"traefik\",protocol=~\"$protocol\"}[$interval])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "状态码200 $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{job=\"traefik\", code=\"200\"}[$interval])) by (method,code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "其他状态码 $interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code!=\"200\"}[$interval])) by (method,code)",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "日志",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{job=\"wssio\"} |= \"RequestProtocol\"| json  | line_format \"Status:{{.OriginStatus}} Client From {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}} Route To {{.ServiceAddr}}\""
    }
   ]
  },
  {
   "title": "$service-所有状态 $interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\",job=\"traefik\",protocol=~\"$protocol\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}