name: 部署

on:
  push:
    branches: [ "main" ]

jobs:
  NodeBuild:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/setup-node@master
    - run: ls
    - run: npm install
    - run: npm run build
