name: 部署

on:
  push:
    branches: [ "main" ]

jobs:
  DockerPull:
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script:
            ls -a
