name: 部署

on:
  push:
    branches: [ "main" ]

jobs:
  NodeBuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Build
      uses: actions/setup-node@master
    - run: npm --registry https://registry.npmmirror.com install
    - run: npm run build
    - run: ls
